dist: trusty
#sudo: required

language: python
python: "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
#script: pytest

# Deployment
env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
#  - 'SFTP_KEY=[base64-encoded-rsa-key]'

# after_success:
# - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
# - curl --ftp-create-dirs
#        -T filename
#        --key /tmp/sftp_rsa
#        sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename