dist: trusty
#sudo: required

language: python
python: "2.7"

before_install:
  - echo "before install"

install:
  - echo "IN install"

before_script:
  - echo "before script"

script:
  - echo "IN script"

after_failure:
  - echo "IN after_failure"

after_success:
  - echo "IN after_success"

after_script:
  - echo "IN after_script"
  - echo "${SFTP_USER}"
  - echo $SFTP_USER
  - ls
  - sftp --version