dist: trusty
#sudo: required

language: python
python: "2.7"

before_install:
  - echo "before install"

install:
  - echo "IN install"

before_script:
  - echo "before script"

script:
  - echo "IN script"

after_failure:
  - echo "IN after_failure"

after_success:
  - echo "IN after_success"

after_script:
  - echo "IN after_script"
  - echo "${SFTP_USER}"
  - echo $SFTP_USER
  - env
  - ls
  - cat ~/.ssh/known_hosts
  - ssh-keyscan -H plato.emptool.com >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - cat ~/.ssh/config
  - cat ~/.ssh/authorized_keys
  - ssh-agent -s
  - ssh-add $ID_RSA_PUB
  - echo test sftp
