dist: trusty
#sudo: required

language: python
python: "2.7"

before_install:
  - echo "before install"

install:
  - echo "IN install"

before_script:
  - echo "before script"

script:
  - echo "IN script"

after_failure:
  - echo "IN after_failure"

after_success:
  - echo "IN after_success"

after_script:
  - echo "IN after_script"
  - echo "${SFTP_USER}"
  - echo $SFTP_USER
  - ls
  - sftp --version
  - sshpass --version
  - ssh-keyscan
  - ssh-keyscan -H plato.emptool.com >> ~/.ssh/known_hosts
  - ls -al
  - echo $ID_RSA_PUB
  - echo $ID_RSA_PUB > ~/.ssh/id_rsa.pub
  - ls -al ~/
  - ls -al ~/.ssh
  - echo test ok
  - cat ~/.ssh/id_rsa.pub
  - echo ${#RSA_ID_PUB}
# - sftp zhixian@plato.emptool.com
# - lftp
