dist: trusty
#sudo: required

language: python
python: "2.7"

before_install:
  - echo "before install"

install:
  - echo "IN install"

before_script:
  - echo "before script"

script:
  - echo "IN script"

after_success:
  - echo "IN after_success"

after_failure:
  - echo "IN after_failure"

# before_deploy:
#   - echo "IN before_deploy"

# deploy:
#   - echo "IN deploy"

# after_deploy:
#   - echo "IN after_deploy"

after_script:
  - echo "IN after_script"
